# Generated by Django 5.0.6 on 2026-05-10 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(db_column='Id_Cliente', max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id_correo', models.CharField(db_column='Id_Correo', max_length=36, primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=255, null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('cliente', models.ForeignKey(db_column='Id_Cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='correos', to='clients.cliente')),
            ],
            options={
                'db_table': 'CORREO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id_direccion', models.CharField(db_column='Id_Direccion', max_length=36, primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, db_column='Calle', max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='Ciudad', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=100, null=True)),
                ('cp', models.CharField(blank=True, db_column='CP', max_length=10, null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('cliente', models.ForeignKey(db_column='Id_Cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='direcciones', to='clients.cliente')),
            ],
            options={
                'db_table': 'DIRECCION_CLIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id_telefono', models.CharField(db_column='Id_Telefono', max_length=36, primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('cliente', models.ForeignKey(db_column='Id_Cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='telefonos', to='clients.cliente')),
            ],
            options={
                'db_table': 'TELEFONO',
                'managed': True,
            },
        ),
    ]
