# Generated by Django 5.0.6 on 2026-05-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='correo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='direccioncliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'managed': False},
        ),
    ]
