# Generated by Django 5.0.6 on 2026-05-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_cliente_options_alter_correo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='correo',
            table='correo',
        ),
        migrations.AlterModelTable(
            name='direccioncliente',
            table='direccion_cliente',
        ),
        migrations.AlterModelTable(
            name='telefono',
            table='telefono',
        ),
    ]
