# Generated by Django 5.0.6 on 2026-05-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.CharField(db_column='Id_Socio', max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('porcentaje_comision', models.DecimalField(blank=True, db_column='Porcentaje_Comision', decimal_places=2, max_digits=5, null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SOCIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(db_column='Id_Usuario', max_length=36, primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, db_column='Usuario', max_length=100, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('nivel_acceso', models.IntegerField(blank=True, db_column='Nivel_Acceso', null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('socio', models.ForeignKey(db_column='Id_Socio', on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarios', to='users.socio')),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': True,
            },
        ),
    ]
