# Generated by Django 5.0.6 on 2026-05-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_socio_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='socio',
            table='socio',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
