# Generated by Django 5.0.6 on 2026-05-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionSocio',
            fields=[
                ('id_comision', models.CharField(db_column='Id_Comision', max_length=36, primary_key=True, serialize=False)),
                ('monto_comision', models.DecimalField(blank=True, db_column='Monto_Comision', decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=50, null=True)),
                ('fecha_calculo', models.DateTimeField(blank=True, db_column='Fecha_Calculo', null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, db_column='Fecha_Pago', null=True)),
                ('pedido', models.ForeignKey(db_column='Id_Pedido', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comisiones', to='orders.pedido')),
                ('socio', models.ForeignKey(db_column='Id_Socio', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comisiones', to='users.socio')),
            ],
            options={
                'db_table': 'COMISION_SOCIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.CharField(db_column='Id_Pago', max_length=36, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=10, null=True)),
                ('metodo', models.CharField(blank=True, db_column='Metodo', max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, db_column='Referencia', max_length=255, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, db_column='Fecha_Pago', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=50, null=True)),
                ('pedido', models.ForeignKey(db_column='Id_Pedido', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagos', to='orders.pedido')),
            ],
            options={
                'db_table': 'PAGO',
                'managed': True,
            },
        ),
    ]
