# Generated by Django 5.0.6 on 2026-05-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_comisionsocio_options_alter_pago_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comisionsocio',
            table='comision_socio',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='pago',
        ),
    ]
