# Generated by Django 5.0.6 on 2026-05-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('providers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPaquete',
            fields=[
                ('id_estado_paquete', models.CharField(db_column='Id_EstadoPaquete', max_length=36, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ESTADO_PAQUETE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.CharField(db_column='Id_Paquete', max_length=36, primary_key=True, serialize=False)),
                ('codigo_activacion', models.CharField(blank=True, db_column='Codigo_Activacion', max_length=100, null=True)),
                ('fecha_pedido_proveedor', models.DateField(blank=True, db_column='Fecha_Pedido_Proveedor', null=True)),
                ('fecha_entrega_proveedor', models.DateField(blank=True, db_column='Fecha_Entrega_Proveedor', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.ForeignKey(db_column='Id_EstadoPaquete', on_delete=django.db.models.deletion.DO_NOTHING, related_name='paquetes', to='logistics.estadopaquete')),
                ('producto', models.ForeignKey(db_column='Id_Producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='paquetes', to='products.producto')),
                ('proveedor', models.ForeignKey(db_column='Id_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='paquetes', to='providers.proveedor')),
            ],
            options={
                'db_table': 'PAQUETE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPaquete',
            fields=[
                ('id_historial_paq', models.CharField(db_column='Id_HistorialPaq', max_length=36, primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(blank=True, db_column='Fecha_Cambio', null=True)),
                ('nota', models.TextField(blank=True, db_column='Nota', null=True)),
                ('estado', models.ForeignKey(db_column='Id_EstadoPaquete', on_delete=django.db.models.deletion.DO_NOTHING, to='logistics.estadopaquete')),
                ('usuario', models.ForeignKey(db_column='Id_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
                ('paquete', models.ForeignKey(db_column='Id_Paquete', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historial_estados', to='logistics.paquete')),
            ],
            options={
                'db_table': 'HISTORIAL_ESTADO_PAQUETE',
                'managed': True,
            },
        ),
    ]
