# Generated by Django 5.0.6 on 2026-05-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_estadopaquete_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadopaquete',
            table='estado_paquete',
        ),
        migrations.AlterModelTable(
            name='historialestadopaquete',
            table='historial_estado_paquete',
        ),
        migrations.AlterModelTable(
            name='paquete',
            table='paquete',
        ),
    ]
