# Generated by Django 5.0.6 on 2026-05-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(db_column='Id_Proveedor', max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('sitio_web', models.CharField(blank=True, db_column='SitioWeb', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id_cupon', models.CharField(db_column='Id_Cupon', max_length=36, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True)),
                ('descuento_porcentaje', models.DecimalField(blank=True, db_column='Descuento_Porcentaje', decimal_places=2, max_digits=5, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, db_column='Fecha_Caducidad', null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('proveedor', models.ForeignKey(db_column='Id_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cupones', to='providers.proveedor')),
            ],
            options={
                'db_table': 'CUPON',
                'managed': True,
            },
        ),
    ]
