# Generated by Django 5.0.6 on 2026-05-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupon',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False},
        ),
    ]
