# Generated by Django 5.0.6 on 2026-05-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_cupon_options_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cupon',
            table='cupon',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
    ]
