# Generated by Django 5.0.6 on 2026-05-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.CharField(db_column='Id_Categoria', max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'CATEGORIA_PRODUCTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(db_column='Id_Producto', max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('precio', models.DecimalField(blank=True, db_column='Precio', decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(db_column='Id_Categoria', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='products.categoriaproducto')),
                ('proveedor', models.ForeignKey(db_column='Id_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='providers.proveedor')),
            ],
            options={
                'db_table': 'PRODUCTO',
                'managed': True,
            },
        ),
    ]
