# Generated by Django 5.0.6 on 2026-05-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriaproducto',
            table='categoria_producto',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
