# Generated by Django 5.0.6 on 2026-05-10 06:52

import datetime
import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('providers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado_pedido', models.CharField(db_column='Id_EstadoPedido', max_length=36, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ESTADO_PEDIDO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.CharField(db_column='Id_Pedido', default=orders.models.generate_uuid_str, max_length=36, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(blank=True, db_column='Fecha_Creacion', default=datetime.date.today, null=True)),
                ('fecha_entrega', models.DateField(blank=True, db_column='Fecha_Entrega', null=True)),
                ('total', models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cliente', models.ForeignKey(db_column='Id_Cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='clients.cliente')),
                ('cupon', models.ForeignKey(blank=True, db_column='Id_Cupon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='providers.cupon')),
                ('direccion', models.ForeignKey(blank=True, db_column='Id_Direccion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clients.direccioncliente')),
                ('estado', models.ForeignKey(blank=True, db_column='Id_EstadoPedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='orders.estadopedido')),
                ('socio', models.ForeignKey(db_column='Id_Socio', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='users.socio')),
            ],
            options={
                'db_table': 'PEDIDO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id_historial', models.CharField(db_column='Id_Historial', default=orders.models.generate_uuid_str, max_length=36, primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(blank=True, db_column='Fecha_Cambio', default=django.utils.timezone.now, null=True)),
                ('nota', models.TextField(blank=True, db_column='Nota', null=True)),
                ('estado', models.ForeignKey(db_column='Id_EstadoPedido', on_delete=django.db.models.deletion.DO_NOTHING, to='orders.estadopedido')),
                ('usuario', models.ForeignKey(db_column='Id_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
                ('pedido', models.ForeignKey(db_column='Id_Pedido', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='orders.pedido')),
            ],
            options={
                'db_table': 'HISTORIAL_ESTADO_PEDIDO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.CharField(db_column='Id_Detalle', default=orders.models.generate_uuid_str, max_length=36, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='PrecioUnitario', decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, db_column='Subtotal', decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(db_column='Id_Producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='products.producto')),
                ('pedido', models.ForeignKey(db_column='Id_Pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.pedido')),
            ],
            options={
                'db_table': 'DETALLE_PEDIDO',
                'managed': True,
            },
        ),
    ]
