# Generated by Django 5.0.6 on 2026-05-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estadopedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historialestadopedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': False},
        ),
    ]
