# Generated by Django 5.0.6 on 2026-05-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_detallepedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallepedido',
            table='detalle_pedido',
        ),
        migrations.AlterModelTable(
            name='estadopedido',
            table='estado_pedido',
        ),
        migrations.AlterModelTable(
            name='historialestadopedido',
            table='historial_estado_pedido',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
    ]
